#! python3
# sendAlert.py - send an email with optional subject/message

import smtplib, passwordGen


def alert(subject="Python Alert", message="An alert was generated by a python script."):
    conn = smtplib.SMTP("smtp.gmail.com", 587)
    conn.ehlo()
    conn.starttls()
    conn.login("allenmattpdev@gmail.com", passwordGen.passGen())

    conn.sendmail("allenmattpdev@gmail.com", "allenmattp@gmail.com",
                  f"Subject: {subject}\n\n"
                  f"{message}")
    conn.quit()